# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [2]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [4]:
# YOUR CODE HERE
my_array1 = np.array([2,3,4,6,7,9])
print("myarray_1 Shape:", my_array1.shape)
print("myarray_1 Type:", my_array1.dtype)

my_array2 = np.array([2,3,"me",4,"John","Sarah"])
print("myarray_2 Shape:",my_array2.shape)
print("myarray_2 Type:", my_array2.dtype)

myarray_1 Shape: (6,)
myarray_1 Type: int64
myarray_2 Shape: (6,)
myarray_2 Type: <U21


the dtype describes how bytes in the array should be interpreted: 
- the first array (my_array1) has an int data type : 64-bit integer number
- the second array (my_array2) has "<U21" which means that it contains 21 characters. The elements of the array are being promoted

---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [5]:
# YOUR CODE HERE
my_array3 = np.array([1,3,7,8,6,10,9,11])
print("shape:", my_array3.shape)
print("size:", my_array3.size)
print("data type:", my_array3.dtype)

shape: (8,)
size: 8
data type: int64


The size represents how many elements are in the array.

---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [6]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE
tabular_layout= np.random.random((num_samples,num_features))
print("Shape:",tabular_layout.shape)

Shape: (100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [7]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE
image = np.random.rand(num_images, num_rows, num_cols, num_channels)
print("Shape:",image.shape)

Shape: (100, 256, 256, 3)


---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [10]:
# YOUR CODE HERE
my_array4 = np.array(([2,4],[3,5],[4,9]))


print("my_array4:\n",my_array4)
print("shape:", my_array4.shape)
print("sum of all elements:",np.sum(my_array4, axis=None))
print("sum of all elements by column:", np.sum(my_array4, axis=0))
print("Float sum of elements by row:",np.sum(my_array4, axis=1 , dtype=float))
print("first row:",my_array4[0])
print("Second row:",my_array4[1])
print("Element at position (1,0):",my_array4[1][0])

my_array4[2,1]= 10
print("my_array4 modified:\n",my_array4)

for element in np.nditer(my_array4):
    print(element)

my_array4:
 [[2 4]
 [3 5]
 [4 9]]
shape: (3, 2)
sum of all elements: 27
sum of all elements by column: [ 9 18]
Float sum of elements by row: [ 6.  8. 13.]
first row: [2 4]
Second row: [3 5]
Element at position (1,0): 3
my_array4 modified:
 [[ 2  4]
 [ 3  5]
 [ 4 10]]
2
4
3
5
4
10


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [11]:
# YOUR CODE HERE
new_array = np.random.random((3,2))
print(new_array)
year_array = np.arange(1991, 2018)
print(year_array, year_array.shape)
print(np.zeros(shape=(3,5,10)))
print(np.ones(shape=(3,5,10)))
print(np.ones(shape=(3,5)) * 5)
print(np.random.normal(loc=0, scale=1, size=10))

[[0.28999571 0.50818013]
 [0.47655793 0.57281228]
 [0.53403895 0.66869277]]
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017] (27,)
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [12]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [13]:
# YOUR CODE HERE
#creating 3D nested array
years_3d = np.arange(1991, 2018).reshape(3,3,3)
print(years_3d)

#flattening array
years_1d = years_3d.flatten()
print(years_1d)

# Add a new axis in front
years_2d = np.expand_dims(years_1d, axis=0)
print(years_2d.shape)

# Remove the first axis
years_1d = np.squeeze(years_2d, axis=None)
print(years_1d.shape)

[[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
(1, 27)
(27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [14]:
# YOUR CODE HERE
array_zeros = np.zeros((3, 3))
array_ones = np.ones((3, 3))

#np.concatenate() examples
print("\nCONCATENATING")
#1. concatenating my_array1 and years1_d
print("1. Concatenated my_array1 & years_1d:\n",np.concatenate((my_array1,years_1d), axis=0))
# 2. Create arrays with different constant values
array_twos = np.full((2, 3), 2)     # Array filled with 2s
array_threes = np.full((2, 3), 3)   # Array filled with 3s
array_fours = np.full((2, 3), 4)    # Array filled with 4s
array_fives = np.full((2, 3), 5)    # Array filled with 5s

# Concatenate along the first axis (rows), then concatenate along the second axis (columns)
concat_combo = np.concatenate((
    np.concatenate((array_twos, array_threes), axis=0),  # Stack twos on top of threes
    np.concatenate((array_fours, array_fives), axis=0)   # Stack fours on top of fives
), axis=1)  # Then stack side by side

# Print result
print("2. Concatenated combo:\n", concat_combo)

# 3-4 Concatenate along rows (axis=0) and columns (axis=1)
# Print results
print("3. Concatenated along axis 0:\n", np.concatenate((array_zeros, array_ones), axis=0))
print("4. Concatenated along axis 1:\n", np.concatenate((array_zeros, array_ones), axis=1))

#using np.stack()
print("\nSTACKING")
# 1. combining arrays
print("1. Stacking myarray1 and 2 0:\n",np.stack((my_array1, my_array2), axis=-1))

# 2. Stack them along a new axis (axis=0)
stacked_array_axis0 = np.stack((array_zeros, array_ones), axis=0)

# 3. Stack them along a new axis (axis=1)
stacked_array_axis1 = np.stack((array_zeros, array_ones), axis=1)

# 4. Stack them along a new axis (axis=2)
stacked_array_axis2 = np.stack((array_zeros, array_ones), axis=2)

# Print the results
print("\n2. Stacked along axis 0:\n", stacked_array_axis0)
print("\n3. Stacked along axis 1:\n", stacked_array_axis1)
print("\n4. Stacked along axis 2:\n", stacked_array_axis2)


CONCATENATING
1. Concatenated my_array1 & years_1d:
 [   2    3    4    6    7    9 1991 1992 1993 1994 1995 1996 1997 1998
 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012
 2013 2014 2015 2016 2017]
2. Concatenated combo:
 [[2 2 2 4 4 4]
 [2 2 2 4 4 4]
 [3 3 3 5 5 5]
 [3 3 3 5 5 5]]
3. Concatenated along axis 0:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
4. Concatenated along axis 1:
 [[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]

STACKING
1. Stacking myarray1 and 2 0:
 [['2' '2']
 ['3' '3']
 ['4' 'me']
 ['6' '4']
 ['7' 'John']
 ['9' 'Sarah']]

2. Stacked along axis 0:
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

3. Stacked along axis 1:
 [[[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]]

4. Stacked along axis 2:
 [[[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]]


---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [15]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [16]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [17]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [18]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [19]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[5.31221554e-01, 2.37281923e-01, 8.72005547e-01, 9.89537574e-01],
       [9.44649530e-01, 2.59047822e-02, 2.41036029e-01, 2.09232762e-01],
       [6.91936843e-01, 7.02465192e-01, 5.92360703e-01, 2.85496978e-01],
       [9.10061264e-02, 4.74607622e-01, 2.44213847e-01, 3.08055169e-02],
       [6.55060658e-01, 9.80750478e-04, 4.46020788e-01, 9.63664756e-01],
       [3.86439740e-01, 4.09421652e-01, 2.32061314e-02, 3.67139198e-02],
       [3.02058733e-01, 9.58056443e-01, 7.91801052e-01, 5.15142500e-01],
       [9.26690622e-02, 6.01623233e-01, 4.45338123e-01, 8.85537478e-01],
       [7.66971472e-01, 4.99193674e-01, 5.89632232e-02, 5.72399954e-01],
       [2.03701092e-01, 4.48716641e-01, 3.28975282e-01, 4.14938107e-01]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [20]:
# YOUR CODE HERE
#computing mean
mean_array= np.mean(my_array, axis=0, keepdims=True)

#computing standard deviation
std_array = np.std(my_array, axis=0, keepdims=True)

#total for broadcasting results
total= mean_array + std_array

# Print the results
print("Mean for each column:\n", mean_array)
print("\nStandard deviation for each column:\n", std_array)

# Standardize the array
standardized_array = (my_array - mean_array) / std_array

# Print the standardized array and its shape
print("\nStandardized array:\n", standardized_array)
print("Shape of standardized array:", standardized_array.shape)

Mean for each column:
 [[0.46657148 0.43582519 0.40439207 0.49034695]]

Standard deviation for each column:
 [[0.28155548 0.27825136 0.27021169 0.34356667]]

Standardized array:
 [[ 0.22961753 -0.71353925  1.73054494  1.45296581]
 [ 1.69798882 -1.47320181 -0.60454839 -0.81822313]
 [ 0.80042969  0.95827025  0.69563471 -0.5962452 ]
 [-1.33389469  0.13937912 -0.59278792 -1.33756119]
 [ 0.66945662 -1.56277561  0.15405964  1.37765927]
 [-0.28460374 -0.09489096 -1.41069374 -1.32036393]
 [-0.58429959  1.8768327   1.43372397  0.07217099]
 [-1.32798845  0.59585707  0.15153323  1.15025863]
 [ 1.06693003  0.22773827 -1.27836382  0.23882701]
 [-0.93363622  0.04633023 -0.27910262 -0.21948825]]
Shape of standardized array: (10, 4)


----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [21]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [22]:
# Crop by removing the first and last two rows and columns
cropped_image_2x2 = my_image[2:-2, 2:-2]
print("\nCropped Image Removing First and Last Two Rows and Columns:\n", cropped_image_2x2)



Cropped Image Removing First and Last Two Rows and Columns:
 [[0.48]]


In [23]:
# YOUR CODE HERE
# Crop by using a border of size 1
cropped_image_border = my_image[1:-1, 1:-1]
print("\nCropped Image with Border of Size 1:\n", cropped_image_border)

#cropping first and last two rows, first and last two columns
cropped_rows = my_image[1:3, 1:3]
print("\nCropped first and last two rows and columns:\n",cropped_rows)

#reversing order
reversed_order = my_image[::-1]
print("\nReversed Order:\n",reversed_order)

#setting images to 0.5 where it is divisible by 2
mod_image = np.where(my_image % 2 == 0, 0.5, my_image)
print("\nImage with Elements Divisible by 2 Set to 0.5:\n", mod_image)


Cropped Image with Border of Size 1:
 [[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]

Cropped first and last two rows and columns:
 [[0.24 0.28]
 [0.44 0.48]]

Reversed Order:
 [[0.8  0.84 0.88 0.92 0.96]
 [0.6  0.64 0.68 0.72 0.76]
 [0.4  0.44 0.48 0.52 0.56]
 [0.2  0.24 0.28 0.32 0.36]
 [0.   0.04 0.08 0.12 0.16]]

Image with Elements Divisible by 2 Set to 0.5:
 [[0.5  0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]
